import 'package:fl_lib/fl_lib.dart';
import 'package:flutter/material.dart';
import 'package:server_box/core/extension/context/locale.dart';

enum ServiceAction {
  start,
  stop,
  restart,
  status,
  enable,
  disable;

  IconData get icon => switch (this) {
    start => Icons.play_arrow,
    stop => Icons.stop,
    restart => Icons.refresh,
    status => Icons.info,
    enable => Icons.power_settings_new,
    disable => Icons.power_off,
  };

  String get displayName => switch (this) {
    start => libL10n.start,
    stop => libL10n.stop,
    restart => libL10n.restart,
    status => l10n.status,
    enable => l10n.enable,
    disable => l10n.disable,
  };
}

enum ServiceManagerType {
  systemd,
  procd,
  openrc;

  String get displayName => switch (this) {
    systemd => 'systemd',
    procd => 'procd',
    openrc => 'OpenRC',
  };

  bool get supportsUserScope => this == systemd;
}

enum ServiceUnitType {
  service,
  socket,
  mount,
  timer;

  static ServiceUnitType? fromString(String? value) {
    return values.firstWhereOrNull((e) => e.name == value?.toLowerCase());
  }
}

enum ServiceScope {
  system,
  user;

  Color? get color => switch (this) {
    system => Colors.red,
    _ => null,
  };
}

/// Where a unit's definition lives, derived from its `FragmentPath`.
///
/// `systemctl list-units` reports every unit the manager has loaded, and on a
/// stock host most of those came with the distribution or were generated by
/// the kernel — a list nobody administers. What an operator actually put on
/// the machine sits under `/etc`, so keeping the path lets the app tell those
/// apart locally instead of showing all of them at once.
enum ServiceOrigin {
  /// `/etc/systemd/system`, `/etc/xdg/systemd/user`, or the user's own
  /// `~/.config/systemd/user` — placed there by whoever administers the host.
  local,

  /// `/lib` or `/usr/lib` — shipped by the distribution or a package.
  vendor,

  /// `/run` — written by a generator and gone on reboot.
  runtime,

  /// No fragment file at all. Mount units the kernel synthesises from
  /// `/proc/self/mountinfo` are the bulk of these: real units with no file
  /// behind them.
  transient,
}

enum ServiceOriginFilter {
  all,
  local;

  /// `/etc` is a path, not prose, so it needs no translation.
  /// [ServiceOrigin.local] also covers `~/.config/systemd/user`, which this
  /// label glosses over — the two are the same idea to whoever reads the list.
  String get displayName => switch (this) {
    all => libL10n.all,
    local => '/etc',
  };

  bool accepts(ServiceUnit unit) => switch (this) {
    all => true,
    local => unit.origin == ServiceOrigin.local,
  };
}

enum ServiceScopeFilter {
  all,
  system,
  user;

  String get displayName => switch (this) {
    all => libL10n.all,
    system => libL10n.system,
    user => libL10n.user,
  };
}

enum ServiceState {
  running,
  stopped,
  failed,
  starting,
  stopping,
  unknown;

  Color? get color => switch (this) {
    failed => Colors.red,
    starting || stopping => Colors.orange,
    _ => null,
  };

  String get displayName => switch (this) {
    running => libL10n.running,
    stopped => libL10n.stopped,
    failed => libL10n.fail,
    starting => l10n.starting,
    stopping => l10n.stopping,
    unknown => libL10n.unknown,
  };
}

final class ServiceUnit {
  const ServiceUnit({
    required this.name,
    required this.type,
    required this.scope,
    required this.state,
    required this.actions,
    this.description,
    this.enabled,
    this.origin = ServiceOrigin.transient,
  });

  final String name;
  final String? description;
  final ServiceUnitType type;
  final ServiceScope scope;
  final ServiceState state;

  /// Null when the manager cannot report startup registration cheaply and
  /// reliably. A false value is different: it means the manager did report
  /// that this service is not registered for startup.
  final bool? enabled;

  /// Defaults to [ServiceOrigin.transient] because that is what a unit with no
  /// path information is: a manager that cannot report one is indistinguishable
  /// from a unit that genuinely has no file.
  final ServiceOrigin origin;

  final List<ServiceAction> actions;

  /// The unit as `systemctl` names it, which is what every command takes.
  String get fullName => '$name.${type.name}';

  ServiceUnit withOrigin(ServiceOrigin origin) => ServiceUnit(
    name: name,
    type: type,
    scope: scope,
    state: state,
    actions: actions,
    description: description,
    enabled: enabled,
    origin: origin,
  );
}

enum ServiceListingNotice {
  userScopeUnavailable,
  detailsUnavailable,
}

final class ServiceListing {
  const ServiceListing({
    required this.units,
    this.notice,
    this.detail,
  });

  final List<ServiceUnit> units;
  final ServiceListingNotice? notice;
  final String? detail;
}
